spring:
  application:
    name: config-server
  cloud:
    config:
      server:
        git:
          uri: https://github.com/angelovicentefilho/jtech_microsservices_config
          default-label: main
          
server:
  port: 8888