spring:
  application:
    name: service-gateway

server:
  port: 8090
  
eureka:
  client:
    service-url:
      default-zone: http://localhost:8761/eureka/
    fetch-registry: true
    

zuul:
  routes:
    products:
      service-id: service-products
      path: /api/products/**
    items:
      service-id: service-items
      path: /api/items/**